[workspace]
members = [
  "bb8_diesel",
  "disposable",
  "juniper_relay",
  "meta_parser",
  "server",
  "typed_id",
]

[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel", rev = "a109351" }
