[package]
name = "typed_id"
version = "0.1.0"
authors = ["Tilman Roeder"]
edition = "2018"

[dependencies]
arrayvec = { version = "0.7", features = ["serde"] }
diesel = "1.4"
juniper = "0.15.5"
nanoid = "0.4"
serde = "1"
