[package]
name = "web_session"
version = "0.1.0"
authors = ["Tilman Roeder"]
edition = "2018"

[dependencies]
base64 = "0.13"
bincode = "1.3"
chrono = { version = "0.4", features = ["serde"] }
hmac = "0.11"
serde = { version = "1", features = ["derive"] }
sha2 = "0.9"
